module.exports = {
  'PREVIOUS':'#previous',
  'SECTION':'#section',
  'NEXT':'#next',
  'SLIDER':'#slider',
  'HOME':'#home',
  'ZOOMIN':'#zoomIn',
  'ZOOMOUT':'#zoomOut',
  'NAVIGATE':  '#navigate',
  'SELECT':'#select',
  'DRAW':'#draw',
  'DRAWPOLYGON':'#drawPolygon',
  'DRAWLine':'#drawLine',
  'ADDPOINT':'#addPoint',
  'DELETEPOINT':'#deletePoint',
  'ADDREGION':'#addRegion',
  'SUBTRACTREGION':'#subtractRegion',
  'SPLITREGION':'#splitRegion',
  'ROTATE':'#rotate',
  'FLIP':'#flipRegion',
  'SIMPLIFY':'#simplify',
  'TOPOLYGON':'#toPolygon',
  'TOBEZIER':'#toBezier',
  'COPY':'#copy',
  'PASTE':'#paste',
  'SAVE':'#save',
  'SCREENSHOT':'#screenshot',
  'DELETE':'#delete',
  'CANVAS': '#openseadragon1'
}
